#OBJS specifies which files to compile as part of the project
OBJS = main.cpp Node.cpp Graph.cpp GUI.cpp

#OBJ_NAME specifies the name of our exectuable
OBJ_NAME = main

#This is the target that compiles our executable
all : $(OBJS)
	g++ $(OBJS) -w -lSDL2 -o $(OBJ_NAME)